version: "3.1"

services:
  storedimolaravel:
    container_name: storedimolaravel
    build:
      context: ./
      dockerfile: ./laravel/storedimo.dockerfile
    volumes:
      - ./laravel/storedimo:/var/www/html:delegated
    ports: 
      - '90:80'
    env_file:
      - ./laravel/config_laravel/datos.env
    # working_dir: /var/www/html/public  # Agrega esta línea

  storedimodb:
    image: postgres
    container_name: storedimodb
    restart: always
    # shm_size: 256mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: softdimo
      POSTGRES_DB: storedimo
    volumes:
      - ./db:/var/lib/postgresql:delegated
    ports:
      - 2023:5432

  storedimoadminer:
    image: adminer
    container_name: storedimoadminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./db:/var/lib/postgresql:delegated
