services:
  storedimolaravel:
    container_name: storedimolaravel
    build:
      context: ./
      dockerfile: ./laravel/storedimo.dockerfile
    volumes:
      - ./laravel/storedimo:/var/www/html:delegated
    ports: 
      - '80:80'
    # env_file:
    #   - ./laravel/storedimo/.env